version: 1.0.1.{build}

# clone directory
clone_folder: c:\projects\omemsis

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: Omemsis.sln
  verbosity: normal

# scripts to run after build
before_build:
  - nuget restore
after_build:
  - cd c:\projects\Omemsis
  - copy c:\projects\Omemsis\Omemsis\bin\Release\Omemsis.exe c:\projects\Omemsis\Omemsis.exe
artifacts:
  - path: Omemsis.exe
    name: Omemsis.exe
